iver56/audiomentations

audiomentations/core/composition.py, tests/test_gaussian_noise.py, tests/test_normalize.py, tests/test_pitch_shift.py, tests/test_shift.py, tests/test_time_stretch.py
=> Add shuffle paramter in Composer

audiomentations/augmentations/transforms.py, demo/demo.py, tests/test_clipping_distortion.py, tests/test_distortion.py
Adds a very simple distortion transformation.
Closes #5
=> Add Distortion transformation

requirements.txt, setup.py
=> Expand librosa version range to cover 0.7.1

audiomentations/augmentations/spectrogram_transforms.py, audiomentations/augmentations/transforms.py, audiomentations/core/transforms_interface.py, audiomentations/core/utils.py, requirements.txt, tests/test_spec_channel_shuffle.py, tests/test_spec_frequency_mask.py, tests/utils.py
#43 #59 
* Implement base classes
* Implement frequency mask
* Implement channel shuffle
=> Lay the foundation for spectrogram transforms

audiomentations/augmentations/transforms.py
=> Fix divide by zero in Addbackgroundnoise

audiomentations/augmentations/transforms.py
=> Configurable LRU cache for transforms that use external sound files

audiomentations/core/composition.py, tests/test_compose.py
Decided in #71 
Also test added on this method in `tests/test_compose.py`
=> Implement `Compose.randomize_parameters`. Close #71

audiomentations/augmentations/transforms.py, tests/test_impulse_response.py
=> Add an option leave_length_unchanged to AddImpulseResponse

README.md
Hi folks !
Thought it'd be nice to add some info about publicly available impulse responses datasets.
I thought about [EchoThief](http://www.echothief.com/), and the [MIT Mc Dermott](http://www.echothief.com/) one that I tried with your repo, and everything seems to work fine!
I did create a short bash script to download these 2 datasets, but I couldn't find any location in your repo to store it. So I decided to not include it in this PR. However, it might be of interested for some of you :)
```
#!/usr/bin/env bash
if [[ "$#" -lt 2 ]] || [[ "$2" != "echothief" && "$2" != "mit" && "$2" != "both" ]]; then
echo "Wrong number of parameters."
echo "Please, call this script in the following way :"
echo "./download_impulse_responses_data.sh /path/where/to/store/ir (echothief|mit|both) <OPTIONAL …
```
=> Add info about pre-existing impulse responses dataset

audiomentations/__init__.py, audiomentations/core/composition.py, tests/test_spec_compose.py
- BaseCompose class added
- Compose class inherited from BaseCompose
- SpecCompose class created according to magnitude spectrogram
- SpecCompose unit test added
=> SpecCompose Implementation

audiomentations/augmentations/spectrogram_transforms.py, audiomentations/core/utils.py, tests/test_spec_compose.py
- SpecChannelShuffle channel fixed channel count changed to dynamic.
- Test sound changed to random gaussian noise with multichannel in test_spec_compose.py
- Multichannel spectrogram check function updated
=> BugFix on SpecChannelShuffle

audiomentations/augmentations/transforms.py, tests/test_tanh_distortion.py
Adds TanhDistortion according to https://github.com/iver56/audiomentations/issues/50
=> Add TanhDistortion

audiomentations/augmentations/transforms.py, tests/test_gaussian_snr.py
Gaussian noise is now generated with `1/noise_std ` instead of `noise_std`.
=> Fix SNR inverse characteristics in AddGaussianSNR

audiomentations/augmentations/transforms.py
Implementing https://github.com/iver56/audiomentations/issues/56
=> Rename AddImpulseResponse to ApplyImpulseResponse

audiomentations/augmentations/transforms.py, tests/test_clip.py
Implements https://github.com/iver56/audiomentations/issues/26
=> Add Clip tranform

audiomentations/core/utils.py
Fixing https://github.com/iver56/audiomentations/issues/78.
=> Follow symlinks by default

audiomentations/augmentations/transforms.py, audiomentations/core/transforms_interface.py
Implementing https://github.com/iver56/audiomentations/issues/115
=> If input is float64, convert to float32 and show a warning

audiomentations/__init__.py, audiomentations/augmentations/transforms.py, tests/test_reverse.py
Adds new augmentation called `Reverse`, which allows to reverse audio. Implements https://github.com/iver56/audiomentations/issues/117.
=> Add Reverse audio

audiomentations/augmentations/transforms.py, audiomentations/core/utils.py, tests/test_band_pass_filter.py, tests/test_high_pass_filter.py, tests/test_low_pass_filter.py
Implementing https://github.com/iver56/audiomentations/issues/7, https://github.com/iver56/audiomentations/issues/8 and https://github.com/iver56/audiomentations/issues/9.
=> Add low-pass, high-pass and band-pass filter transforms

audiomentations/__init__.py, audiomentations/augmentations/spectrogram_transforms.py, audiomentations/core/composition.py, tests/test_some_of.py
+ tests (mostly copy pasted from the tests of OneOf).
=> Added SomeOf

README.md
=> Fix highpass typo in README

README.md, audiomentations/__init__.py, audiomentations/augmentations/add_short_noises.py, audiomentations/augmentations/gain_transition.py, demo/demo.py, tests/test_add_short_noises.py, tests/test_gain_transition.py
=> Implement GainTransition

README.md, audiomentations/augmentations/mp3_compression.py, audiomentations/augmentations/pitch_shift.py, audiomentations/augmentations/time_stretch.py, audiomentations/core/audio_loading_utils.py, requirements.txt, setup.py
=> Add support for librosa 0.9.0

audiomentations/augmentations/add_background_noise.py, audiomentations/core/transforms_interface.py, demo/demo.py, tests/test_add_background_noise.py
=> Add the possibility of transforming background noise before it gets mixed in

audiomentations/__init__.py, audiomentations/augmentations/padding.py, demo/demo.py, tests/test_padding.py
Attempt to implement https://github.com/iver56/audiomentations/issues/123.
=> Add Padding

audiomentations/augmentations/add_short_noises.py, demo/demo.py, tests/test_add_short_noises.py
=> Add noise_transform in AddShortNoises

audiomentations/augmentations/add_background_noise.py, audiomentations/augmentations/add_short_noises.py, audiomentations/augmentations/apply_impulse_response.py, audiomentations/core/utils.py, tests/test_utils.py
Attempt to implement https://github.com/iver56/audiomentations/issues/187 , with application to other augmentations as well. Replaced `get_file_paths()` with `find_audio_files_in_paths()` from `torch-audiomentations`.
=> Allow augmentations to accept a list of files

README.md, audiomentations/__init__.py, audiomentations/augmentations/limiter.py, audiomentations/augmentations/mp3_compression.py, demo/demo.py, requirements.txt, setup.py, tests/test_limiter.py
=> Add Limiter transform

audiomentations/augmentations/add_short_noises.py
Implements https://github.com/iver56/audiomentations/issues/224.
=> Change default of noise_rms in add short noise transform

audiomentations/augmentations/limiter.py, tests/test_limiter.py
=> Test and handle digital silence input in Limiter

audiomentations/augmentations/add_short_noises.py
=> Change default of noise_rms from relative to relative_to_whole_input

audiomentations/augmentations/mp3_compression.py, tests/test_mp3_compression.py
=> Avoid distorting too loud inputs in Mp3Compression

docs/guides/multichannel_audio_array_shapes.md, docs/index.md, mkdocs.yml
https://github.com/iver56/audiomentations/issues/274
=> Add a guide on multichannel audio array shapes

audiomentations/augmentations/add_background_noise.py, audiomentations/augmentations/add_gaussian_snr.py, audiomentations/augmentations/add_short_noises.py, audiomentations/augmentations/gain.py, audiomentations/augmentations/gain_transition.py, audiomentations/augmentations/loudness_normalization.py, demo/demo.py, demo/generate_examples_for_doc.py, docs/waveform_transforms/add_background_noise.md, docs/waveform_transforms/add_gaussian_snr.md, docs/waveform_transforms/add_short_noises.md, docs/waveform_transforms/gain.md, docs/waveform_transforms/gain_transition.md, docs/waveform_transforms/loudness_normalization.md, tests/test_add_background_noise.py, tests/test_add_short_noises.py, tests/test_compose.py, tests/test_gain.py, tests/test_gaussian_snr.py, tests/test_lambda.py, tests/test_loudness_normalization.py, tests/test_one_of.py, tests/test_post_gain.py, tests/test_some_of.py
=> Rename "_in_db" args to "_db"

audiomentations/core/transforms_interface.py, tests/test_gain.py
=> Increase the threshold for raising WrongMultichannelAudioShape

docs/waveform_transforms/time_stretch.md
Close https://github.com/iver56/audiomentations/issues/310
=> Add note on audio quality in TimeStretch docs

docs/waveform_transforms/pitch_shift.md, docs/waveform_transforms/time_stretch.md
Related to https://github.com/iver56/audiomentations/issues/316
=> Link to pitch shift alternatives in docs

audiomentations/augmentations/add_color_noise.py, docs/waveform_transforms/add_color_noise.md, mkdocs.yml
=> Update AddColorNoise docs

audiomentations/__init__.py, audiomentations/augmentations/aliasing.py, tests/test_aliasing.py
Attempt to implement https://github.com/iver56/audiomentations/issues/261.
=> Add Aliasing

audiomentations/augmentations/limiter.py, docs/waveform_transforms/limiter.md, requirements.txt, tests/test_limiter.py
Close https://github.com/iver56/audiomentations/issues/335
=> Avoid delay (zeros in the start) in Limiter output

audiomentations/augmentations/room_simulator.py
For small `p` it will save a lot of time.
=> Don't calculate heavy room parameters if augmentation is not going to be applied

audiomentations/augmentations/add_short_noises.py
This bug was introduced in 0.36.1
TODO: Write a test that reproduces the edge case
=> Handle an edge case where AddShortNoises could raise ValueError("Cannot input empty array")

audiomentations/augmentations/add_background_noise.py, tests/test_add_background_noise.py, tests/utils.py
=> Reproduce and fix a logic bug that led to wrong noise offset in AddBackgroundNoise
