- audiomentations/augmentations/transforms.py
sosfilt() function eliminates NaN values (they're now 0 instead). Also, i fixed the upper bound of the "freq_start" parameter. For example, let's take the worst case scenario ("bandwidth" and "freq_start" equal to their upper bound). That means that highcut will be equal to the Nyquist frequency.
SInce the filter's critical frequencies should be 0 < Wn <1, we are now making sure that this type of error will never occur.
> Fix bug in frequency mask

- demo/demo.py
Some app can't open float64 format wav file, such as Window Media Player and Praat.
> save wav files as float32 format

- README.md
- audiomentations/__init__.py
- audiomentations/augmentations/transforms.py
- audiomentations/core/utils.py
- demo/demo.py
- requirements.txt
- setup.py
- tests/test_mp3_compression.py
It's not really ideal, since it writes to disk, but at least it is functional.
Close https://github.com/iver56/audiomentations/issues/37
> Implement Mp3Compression transform

- audiomentations/core/audio_loading_utils.py
add 32-bit support for loading wav files in audio_loading_utils.py
> add support for 32-bit loading in the load_wav_file function in

- audiomentations/augmentations/transforms.py
- tests/test_shift.py
* Add a `fade` and a `fade_duration` parameter in
`audiomentations.augmentations.transforms.Shift`
* Add the corresponding tests
There are cases where a shift transform without rollover would introduce abrupt changes from zero to non-zero samples leading to transients such as ones in the following image:
For this reason I have made the following pull request which adds a `fade: bool` and a `fade_duration` `int` or `float` to `Shift.__init__`. When `fade_duration` is an int the fade is in samples while when its a `float` it is a time duration.
> Add a fade option in the Shift transform

- audiomentations/augmentations/transforms.py
Zero signal will yield max_value to be 0, hence divide by zero error will occur. This commit avoids the bug.
> Fix a bug in AddImpulseResponse when samples = zero signal.

- audiomentations/core/audio_loading_utils.py
This PR fixes #101 
- convert np.float64 to np.float32 in load_wav_file()
> support np.float64 in load_wav_file()

- README.md
- audiomentations/__init__.py
- audiomentations/core/composition.py
- tests/test_one_of.py
Also add `apply_to_children` argument in some methods in BaseCompose. It defaults to `True`, so the change is backwards compatible.
#61
> Implement OneOf. Refactor compose classes. 

- audiomentations/augmentations/add_short_noises.py
- tests/test_add_short_noises.py
Modified AddShortNoises transform. Added the option "relatively_to_whole_file" in the parameter "noise_rms". so that short noises can be added relatively to the power of the whole clean file and not just to the power of the samples where they are inserted (default behaviour). This has been implemented to address some shortcomings of the default option "relative", like to be able to add short noises even in relatively silent periods.
> Added option in addshortnoise

- tests/test_filter_transforms.py
What the title says. Copied and pasted from  TestHighPassFilterTransform but changed frequencies of interest, gains of interest, and tolerances accordingly.
> Add unit test for LowPassFilter transform

- README.md
- audiomentations/augmentations/padding.py
- audiomentations/core/transforms_interface.py
- demo/demo.py
- tests/test_padding.py
- tests/test_some_of.py
* Rewrite test code for pytest, so I can use `pytest.mark.parametrize`
* Fix support for mono 2D array
* Fix support for multichannel 2D array that was not stereo
* Move pad width variable to randomize_parameters
* Add pad_section parameter
* Replace with padding instead of inserting padding
* Remove edge option, because it would be result in silence with an "arbitrary" DC offset, which I guess is not a useful way to pad audio
* Rename "constant" to "silence" to be more specific
* Add various cases to the demo script
* Add support for min_fraction=0.0, min_fraction==max_fraction and max_fraction=1.0
* Fix whitespace in padding.py in accordance with the code format of the rest of the repo
* Tweak default value of min_fraction and max_fraction
Close #123
> Tweak Padding

- tests/test_filter_transforms.py
- Extend the tests to cover n channel cases instead of just two.
- Add missing multichannel test for the Lowpass filter
> Add multichannel audio tests

- tests/test_gaussian_snr.py
- tests/test_load_sound_files.py
- tests/test_loudness_normalization.py
- tests/test_shift.py
- tests/test_spec_channel_shuffle.py
- tests/test_time_mask.py
- tests/test_utils.py
Implements https://github.com/iver56/audiomentations/issues/176, except from `unittest.mock` in `test_room_simulator.py`. I can replace it with `pytest-mock` if necessary.
> Unittest to pytest

- audiomentations/augmentations/add_background_noise.py
Fixed a bug where the rms of the background nosie would be calculated before applying oprtional transforms to the background noise.
Should I add a test for that ?
> Moved the calculation of noise_rms in the background noise transform

- audiomentations/augmentations/room_simulator.py
This PR specifies correctly the room corner coordinates when building the shoebox room. Before I accidentally had the `x` and `y` coordinates swapped in one case which lead to a microphone leaving the room borders in some cases and causing the behaviour in #201.
Fixes #201
> Use the correct  corner coordinates when constructing the shoebox room

- audiomentations/augmentations/shift.py
- tests/test_shift.py
This PR enables to freeze the Shift transform and then to use it on audio with different sample rates. As it was before, the `num_places_to_shift` would still be the same after freezing the parameters no matter the sample rate.
> modify shift and add test

- audiomentations/core/transforms_interface.py
- docs/guides/multichannel_audio_array_shapes.md
- tests/test_gain.py
https://github.com/iver56/audiomentations/issues/274
> Raise exception instead of warning when multichannel audio has wrong shape

- audiomentations/augmentations/shift.py
- audiomentations/core/composition.py
- demo/demo.py
- demo/generate_examples_for_doc.py
- docs/changelog.md
- docs/waveform_transforms/shift.md
- tests/test_compose.py
- tests/test_one_of.py
- tests/test_shift.py
- tests/test_some_of.py
* Add support for "seconds" and "samples" in addition to "fraction", just like in torch-audiomentations
* Remove `fade` parameter, and use `fade_duration=0` for disabling fading
* Switch from linear fade to a smoother fade curve to reduce unwanted artifacts
* Change the default fade duration, since the fade curve is smoother now
Breaking changes, I know. I didn't do the whole backwards compatibility dance this time because it would take a lot of extra time and clutter the code. audiomentations is still in alpha, so the API is technically not stable. I will document the API changes well in the changelog.
> Improve Shift

- audiomentations/augmentations/limiter.py
- audiomentations/augmentations/mp3_compression.py
- audiomentations/augmentations/normalize.py
- audiomentations/core/utils.py
- demo/generate_examples_for_doc.py
- tests/test_post_gain.py
This way of computing the minmax is roughly 3x faster and uses less memory because it doesn't allocate memory for a new audio ndarray
> Optimize max abs calculations in terms of memory and speed

- audiomentations/augmentations/tanh_distortion.py
- audiomentations/core/utils.py
- requirements.txt
- setup.py
- tests/test_add_background_noise.py
- tests/test_tanh_distortion.py
Speed up AddBackgroundNoise, AddColorNoise, AddGaussianSNR, AddShortNoises and TanhDistortion when processing mono audio. numpy-rms has not optimized processing of stereo/multichannel audio yet, although it works.
https://github.com/nomonosound/numpy-rms performs very fast RMS calculations, as it is written in C with SIMD optimizations. Compatibility is good, with support for Windows, macOS, musllinux, manylinux, Python 3.8-3.12, Arm, x86-64
For example, TanhDistortion becomes ~20% faster, and AddBackgroundNoise becomes up to ~70% faster
> Make RMS calculations faster by using numpy-rms

- audiomentations/augmentations/mp3_compression.py
Why? Because flatten() _always_ makes a copy of the array, which is not necessary/desired here. `ravel` only makes a copy if it is needed. Hence ravel is faster.
> Make Mp3Compression slightly faster by replacing flatten with ravel

- setup.py
All patched version of Python 3.12.* should be allowed, not just 3.12.0.
> Allow all 3.12 patches

- audiomentations/augmentations/time_mask.py
`int(t * 0.1)` may equal to 0.  In this case we skip fading, rather than raising an error.
> Fix an error when fade_length = 0.

- setup.py
The current setup.py (see below) restricts numpy to versions below 2, which prevents installing numpy 2 from PyPI. I have updated it to allow compatibility with numpy 2.
OLD:
```
install_requires=[
"numpy>=1.22.0,<2",
"numpy-minmax>=0.3.0,<1",
"numpy-rms>=0.4.2,<1",
"librosa>=0.8.0,!=0.10.0,<0.11.0",
"python-stretch>=0.3.1,<1",
"scipy>=1.4,<2",
"soxr>=0.3.2,<1.0.0",
]
```
NEW:
```
install_requires=[
"numpy>=1.22.0,<3",
"numpy-minmax>=0.4.0,<1",
"numpy-rms>=0.5.0,<1",
"librosa>=0.8.0,!=0.10.0,<0.11.0",
"python-stretch>=0.3.1,<1",
"scipy>=1.4,<2",
"soxr>=0.3.2,<1.0.0",
]
```
> Update setup.py allowing numpy 2

- audiomentations/augmentations/repeat_part.py
- audiomentations/augmentations/time_mask.py
- audiomentations/core/utils.py
- demo/demo.py
- tests/test_utils.py
We also default to fade=True from now on, to avoid unwanted clicks. That is a better default.
Close https://github.com/iver56/audiomentations/issues/380
> Apply smoother fade in TimeMask

- audiomentations/core/composition.py
- audiomentations/core/sampling.py
- docs/index.md
- tests/test_one_of.py
- tests/test_sampling.py
This addition should leave all existing scripts working the same, but allow for an optional argument for `OneOf` that allows weighted selection of the transform, instead of uniform random. 
If `weights` are not supplied, behavior will default to the way it has always been (uniform random), so this is fully backwards compatible :)
I have a large number of impulse response (IR) files that I wish to use at random in some augmentations for a model I am training, for example from my repo: [impulse-response-audio-files](https://github.com/worldveil/impulse-response-audio-files).
However, not all categories of these IRs are equally as important to our usecase, and as such, we'd like to upsample certain classes (ie: venues, large rooms), and downsample others (ie: small rooms, misc other IRs). …
> Add optional weights argument to OneOf for weighted random selection

- audiomentations/augmentations/time_mask.py
- demo/demo.py
- docs/waveform_transforms/time_mask.md
- tests/test_time_mask.py
* Add `fade_duration` argument and remove `fade`
* Add `mask_location` argument
* Improve performance by ~50% compared to v0.40.0
* Adjust default value of `max_band_part` and `max_band_part` - Close #249
> Improve TimeMask
